# Generated by Django 4.2.3 on 2023-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_pledge_date_created_pledge_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(),
        ),
    ]
